import { 
  Business, 
  Product, 
  Review, 
  User, 
  ForumThread, 
  RFQ, 
  Quotation 
} from '@/lib/types';

/* Mock Users */
export const mockUsers: User[] = [
  {
    id: 'user_1',
    email: 'admin@electromart.com',
    name: 'Admin User',
    role: 'admin',
    phone: '+91-9876543210',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_2',
    email: 'customer@example.com',
    name: 'Rajesh Kumar',
    role: 'customer',
    phone: '+91-9123456789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_3',
    email: 'business@electromart.com',
    name: 'Priya Electronics',
    role: 'business_owner',
    phone: '+91-9234567891',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
];

/* Mock Suppliers/Businesses */
export const mockSuppliers: Business[] = [
  {
    id: 'supplier_1',
    name: 'Phoenix Electronics India',
    legalName: 'Phoenix Electronics Private Limited',
    description: 'Leading supplier of electronic components in India with 15+ years of experience. We specialize in semiconductors, passive components, and IoT modules.',
    logo: 'https://api.dicebear.com/7.x/icons/svg?seed=phoenix',
    banner: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=400&fit=crop',
    businessType: ['distributor', 'wholesaler'],
    gst: '27AABCP1234H1Z0',
    pan: 'AABCP1234H',
    msme: true,
    yearEstablished: 2009,
    employees: 50,
    annualRevenue: '10-50 Cr',
    website: 'https://phoenixelectronics.com',
    email: 'sales@phoenix-electronics.com',
    phone: '+91-22-4098-8888',
    whatsapp: '+91-98765-43210',
    linkedIn: 'https://linkedin.com/company/phoenix-electronics',
    address: {
      street: '123 Tech Park, Electronics City',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
      country: 'India',
    },
    factoryAddress: {
      street: 'Industrial Area, Plot 45',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '412101',
      country: 'India',
    },
    certifications: {
      iso: true,
      rohs: true,
      bis: true,
      ce: false,
      iec: true,
    },
    gallery: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1536678516875-08ce68d36206?w=600&h=400&fit=crop',
    ],
    badges: {
      verified: true,
      topRated: true,
      fastDelivery: true,
      manufacturer: false,
      exporter: true,
      trustedSince: 2009,
    },
    stats: {
      responseRate: 98,
      averageDeliveryTime: '2-3 days',
      responseTimeHours: 2,
      ordersCompleted: 1250,
      repeatCustomers: 450,
      overallScore: 94,
    },
    products: ['product_1', 'product_2', 'product_3', 'product_4', 'product_5'],
    reviews: ['review_1', 'review_2', 'review_3'],
    rating: 4.8,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'supplier_2',
    name: 'TechCore Components',
    legalName: 'TechCore Components Ltd',
    description: 'Specialist in microcontrollers, development boards, and IoT solutions. Direct partnerships with leading manufacturers.',
    logo: 'https://api.dicebear.com/7.x/icons/svg?seed=techcore',
    banner: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=400&fit=crop',
    businessType: ['authorized_dealer', 'distributor'],
    gst: '09AACCT1234F1Z1',
    pan: 'AACCT1234F',
    msme: false,
    yearEstablished: 2015,
    employees: 35,
    annualRevenue: '5-10 Cr',
    website: 'https://techcore.in',
    email: 'info@techcore.in',
    phone: '+91-40-6632-2233',
    whatsapp: '+91-98765-54321',
    address: {
      street: 'Survey 45, Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      country: 'India',
    },
    certifications: {
      iso: true,
      rohs: true,
      bis: false,
      ce: true,
      iec: false,
    },
    gallery: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
    ],
    badges: {
      verified: true,
      topRated: true,
      fastDelivery: false,
      manufacturer: true,
      exporter: true,
      trustedSince: 2015,
    },
    stats: {
      responseRate: 95,
      averageDeliveryTime: '3-4 days',
      responseTimeHours: 4,
      ordersCompleted: 890,
      repeatCustomers: 320,
      overallScore: 92,
    },
    products: ['product_6', 'product_7', 'product_8'],
    reviews: ['review_4', 'review_5'],
    rating: 4.6,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: 'supplier_3',
    name: 'Electro Solutions Hub',
    legalName: 'Electro Solutions Hub Private Limited',
    description: 'Complete solution provider for industrial electronics, sensors, and automation components.',
    logo: 'https://api.dicebear.com/7.x/icons/svg?seed=electro',
    banner: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1200&h=400&fit=crop',
    businessType: ['manufacturer', 'trader'],
    gst: '19AAFFL1234K1Z5',
    pan: 'AAFFL1234K',
    msme: true,
    yearEstablished: 2011,
    employees: 75,
    annualRevenue: '25-50 Cr',
    website: 'https://electrosolutions.co.in',
    email: 'contact@electrosolutions.co.in',
    phone: '+91-11-4132-8888',
    whatsapp: '+91-98765-65432',
    address: {
      street: 'Plot B-2, Industrial Sector',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110026',
      country: 'India',
    },
    factoryAddress: {
      street: 'Phase 1, Industrial Estate',
      city: 'Greater Noida',
      state: 'Uttar Pradesh',
      pincode: '201308',
      country: 'India',
    },
    certifications: {
      iso: true,
      rohs: true,
      bis: true,
      ce: true,
      iec: true,
    },
    gallery: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600&h=400&fit=crop',
    ],
    badges: {
      verified: true,
      topRated: true,
      fastDelivery: true,
      manufacturer: true,
      exporter: true,
      trustedSince: 2011,
    },
    stats: {
      responseRate: 99,
      averageDeliveryTime: '1-2 days',
      responseTimeHours: 1,
      ordersCompleted: 2100,
      repeatCustomers: 650,
      overallScore: 96,
    },
    products: ['product_9', 'product_10', 'product_11', 'product_12'],
    reviews: ['review_6', 'review_7', 'review_8'],
    rating: 4.9,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-17T00:00:00Z',
  },
];

/* Mock Products */
export const mockProducts: Product[] = [
  {
    id: 'product_1',
    name: 'Samsung 18650 Lithium Ion Battery 3000mAh',
    category: 'battery',
    brand: 'Samsung',
    manufacturer: 'Samsung SDI',
    manufacturerPartNumber: 'ICR18650-30B',
    supplierPartNumber: 'SAM-ICR18650-30B',
    description: 'High-performance 18650 lithium-ion battery with 3000mAh capacity. Ideal for flashlights, power tools, and portable devices.',
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_1',
    stock: 450,
    minOrderQuantity: 10,
    price: 245,
    leadTime: '2-3 days',
    packaging: 'Blister pack (10 pcs)',
    countryOfOrigin: 'South Korea',
    hsnCode: '8507600090',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.7,
    reviewCount: 125,
    specs: {
      voltage: 3.7,
      capacity: 3000,
      chemistry: 'Lithium Ion',
      rechargeable: true,
      chargingTime: '4-5 hours',
      maxDischargeCurrent: 30,
      protectionCircuit: true,
      diameter: 18.3,
      operatingTemperature: '-10 to 65°C',
      dimensions: '65mm x 18.3mm',
      weight: 43,
      certifications: ['CE', 'FCC', 'RoHS'],
    },
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'product_2',
    name: 'Murata 100µF 16V Ceramic Capacitor',
    category: 'capacitor',
    brand: 'Murata',
    manufacturer: 'Murata Manufacturing',
    manufacturerPartNumber: 'GRM31CR61A107KA19L',
    supplierPartNumber: 'MUR-GRM31CR61A107KA19L',
    description: 'MLCC ceramic capacitor with 100µF capacitance and 16V rating. Surface mount (0805 package).',
    images: [
      'https://images.unsplash.com/photo-1578926314433-d01baf8faad8?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_2',
    stock: 5000,
    minOrderQuantity: 100,
    price: 8.5,
    leadTime: '1-2 days',
    packaging: 'Tape and reel (3000 pcs)',
    countryOfOrigin: 'Japan',
    hsnCode: '8532210000',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.9,
    reviewCount: 340,
    specs: {
      capacitance: 100,
      voltage: 16,
      tolerance: 10,
      dielectricType: 'Ceramic X7R',
      esr: 0.08,
      rippleCurrent: 120,
      packageType: 'smd',
      size: '0805',
      temperature: '-55 to 125°C',
      operatingTemperature: '-55 to 125°C',
    },
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-11T00:00:00Z',
  },
  {
    id: 'product_3',
    name: 'Vishay 10kΩ 1/4W Carbon Film Resistor',
    category: 'resistor',
    brand: 'Vishay',
    manufacturer: 'Vishay Intertechnology',
    manufacturerPartNumber: 'CFM-10K-1/4W',
    supplierPartNumber: 'VIS-CFM-10K-1/4W',
    description: 'Metal film resistor 10kΩ with 5% tolerance. Axial leaded, ¼W power rating.',
    images: [
      'https://images.unsplash.com/photo-1586253408359-c75ea2a9c663?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_1',
    stock: 10000,
    minOrderQuantity: 50,
    price: 0.5,
    leadTime: '1 day',
    packaging: 'Tube (100 pcs)',
    countryOfOrigin: 'India',
    hsnCode: '8533210020',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.8,
    reviewCount: 520,
    specs: {
      resistance: 10000,
      tolerance: 5,
      powerRating: 0.25,
      packageType: 'through_hole',
      size: 'Axial',
      temperatureCoefficient: '±100ppm/°C',
      currentRating: 25,
    },
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'product_4',
    name: 'STMicroelectronics STM32F103RB Microcontroller',
    category: 'microcontroller',
    brand: 'STMicroelectronics',
    manufacturer: 'STMicroelectronics',
    manufacturerPartNumber: 'STM32F103RBT6',
    supplierPartNumber: 'STM-STM32F103RBT6',
    description: 'ARM Cortex-M3 microcontroller with 128KB Flash, 20KB SRAM. Popular for industrial and embedded applications.',
    images: [
      'https://images.unsplash.com/photo-1517420681949-d78e60b893e2?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_3',
    stock: 280,
    minOrderQuantity: 5,
    price: 2450,
    leadTime: '2-3 days',
    packaging: 'LQFP100 package',
    countryOfOrigin: 'Italy',
    hsnCode: '8542311200',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.9,
    reviewCount: 890,
    specs: {
      flash: 128,
      ram: 20,
      core: 'ARM Cortex-M3',
      architecture: '32-bit',
      frequency: 72,
      adc: 3,
      gpio: 80,
      timers: 4,
      pwm: 12,
      uart: 3,
      spi: 2,
      i2c: 2,
      packageType: 'LQFP100',
      powerConsumption: '45mA @ 72MHz',
      operatingTemperature: '-40 to 85°C',
    },
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-13T00:00:00Z',
  },
  {
    id: 'product_5',
    name: 'Arduino Uno R3 Development Board',
    category: 'development_board',
    brand: 'Arduino',
    manufacturer: 'Arduino',
    manufacturerPartNumber: 'A000066',
    supplierPartNumber: 'ARD-UNO-R3',
    description: 'Official Arduino Uno R3 board with ATmega328P microcontroller. Includes USB interface and prototyping area.',
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_2',
    stock: 150,
    minOrderQuantity: 1,
    price: 3200,
    leadTime: '3-4 days',
    packaging: 'Individual box',
    countryOfOrigin: 'Italy',
    hsnCode: '8471410000',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.8,
    reviewCount: 456,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-14T00:00:00Z',
  },
  {
    id: 'product_6',
    name: 'DHT22 Temperature & Humidity Sensor',
    category: 'sensor',
    brand: 'Aosong',
    manufacturer: 'Aosong Electronics',
    manufacturerPartNumber: 'DHT22',
    supplierPartNumber: 'DHT22-SENSOR',
    description: 'Digital temperature and humidity sensor with excellent accuracy. Operating range: -40 to 80°C.',
    images: [
      'https://images.unsplash.com/photo-1596994871424-f6fde58e3ee1?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_1',
    stock: 600,
    minOrderQuantity: 10,
    price: 425,
    leadTime: '2-3 days',
    packaging: 'PCB mount',
    countryOfOrigin: 'China',
    hsnCode: '9030899090',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.6,
    reviewCount: 280,
    specs: {
      type: 'Digital Temperature & Humidity',
      outputType: 'Digital (1-wire)',
      rangeMin: -40,
      rangeMax: 80,
      accuracy: '±0.5°C',
      supplyVoltage: '3.3V - 5V',
      operatingTemperature: '-40 to 80°C',
      packageType: 'Through-hole',
    },
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'product_7',
    name: 'Hirose DF13 6-Pin Connector',
    category: 'connector',
    brand: 'Hirose',
    manufacturer: 'Hirose Electric',
    manufacturerPartNumber: 'DF13-6DS',
    supplierPartNumber: 'HIR-DF13-6DS',
    description: 'JST-compatible 6-pin right-angle connector. Commonly used in drone and robotics applications.',
    images: [
      'https://images.unsplash.com/photo-1622244898842-c5ce4baf6835?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_3',
    stock: 2000,
    minOrderQuantity: 20,
    price: 65,
    leadTime: '1-2 days',
    packaging: 'Tube (100 pcs)',
    countryOfOrigin: 'Japan',
    hsnCode: '8536690090',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.7,
    reviewCount: 340,
    specs: {
      pitch: 2.0,
      currentRating: 3,
      voltageRating: 250,
      orientation: 'Right-angle',
      gender: 'male',
      pins: 6,
      connectorType: 'Header',
      mountingType: 'Through-hole',
      housingMaterial: 'Polyamide',
      ipRating: 'IP20',
    },
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-16T00:00:00Z',
  },
  {
    id: 'product_8',
    name: '5mm Red LED 20mA',
    category: 'led',
    brand: 'Kingbright',
    manufacturer: 'Kingbright Electronics',
    manufacturerPartNumber: 'L-93R3BHJ-LF',
    supplierPartNumber: 'KB-LED-5MM-RED',
    description: 'Standard 5mm red LED with 20mA forward current. Bright and reliable for all LED applications.',
    images: [
      'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=400&h=400&fit=crop',
    ],
    supplierId: 'supplier_2',
    stock: 5000,
    minOrderQuantity: 100,
    price: 2.5,
    leadTime: '1 day',
    packaging: 'Reel (1000 pcs)',
    countryOfOrigin: 'Taiwan',
    hsnCode: '8541410000',
    lifecycle: 'active',
    rohs: true,
    reach: true,
    rating: 4.8,
    reviewCount: 650,
    specs: {
      color: 'Red',
      wavelength: 625,
      luminousIntensity: 800,
      forwardCurrent: 20,
      forwardVoltage: 2.0,
      packageType: '5mm DIP',
      operatingTemperature: '-10 to 60°C',
      viewingAngle: 20,
    },
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-17T00:00:00Z',
  },
];

/* Mock Reviews */
export const mockReviews: Review[] = [
  {
    id: 'review_1',
    productId: 'product_1',
    supplierId: 'supplier_1',
    userId: 'user_2',
    userName: 'Rajesh Kumar',
    rating: 5,
    title: 'Excellent Quality Batteries',
    content: 'Received high-quality batteries. Great value for money. Delivery was on time as promised.',
    verified: true,
    helpful: 24,
    unhelpful: 1,
    categories: {
      quality: 5,
      originality: 5,
      packaging: 5,
      price: 4,
      delivery: 5,
      support: 5,
    },
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'review_2',
    productId: 'product_2',
    supplierId: 'supplier_1',
    userId: 'user_2',
    userName: 'Priya Sharma',
    rating: 4,
    title: 'Good capacitors, Fast delivery',
    content: 'Received exactly as described. Seller responded to my queries quickly. Packaging was secure.',
    verified: true,
    helpful: 18,
    unhelpful: 2,
    categories: {
      quality: 4,
      originality: 4,
      packaging: 4,
      price: 4,
      delivery: 5,
      support: 4,
    },
    createdAt: '2024-01-11T00:00:00Z',
    updatedAt: '2024-01-11T00:00:00Z',
  },
];

/* Mock Forum Threads */
export const mockForumThreads: ForumThread[] = [
  {
    id: 'thread_1',
    authorId: 'user_2',
    authorName: 'Rajesh Kumar',
    authorRole: 'customer',
    title: 'Looking for 470µF Capacitor with ESR < 0.02Ω',
    content: 'I need a 470µF capacitor with ESR below 0.02 Ohm and diameter less than 10mm. Any suggestions for suppliers?',
    type: 'requirement',
    tags: ['capacitor', 'low-esr', 'urgent'],
    replies: [],
    views: 145,
    likes: 12,
    solved: true,
    createdAt: '2024-01-14T00:00:00Z',
    updatedAt: '2024-01-16T00:00:00Z',
  },
];

/* Mock RFQs */
export const mockRFQs: RFQ[] = [
  {
    id: 'rfq_1',
    customerId: 'user_2',
    customerName: 'Rajesh Kumar',
    title: 'Electronic Components for Solar Charger Project',
    description: 'We need to procure components for a portable solar charger. See BOM attached.',
    items: [
      {
        id: 'rfq_item_1',
        partNumber: 'STM32F103RBT6',
        componentName: 'STM32F103RB Microcontroller',
        quantity: 50,
        specifications: '128KB Flash, 20KB RAM',
      },
      {
        id: 'rfq_item_2',
        partNumber: 'DHT22',
        componentName: 'Temperature Humidity Sensor',
        quantity: 100,
      },
    ],
    targetPrice: '₹2,50,000',
    budgetRange: { min: 200000, max: 300000 },
    deliveryDate: '2024-02-15',
    priority: 'high',
    status: 'quoted',
    quotations: [],
    createdAt: '2024-01-10T00:00:00Z',
    expiresAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-01-16T00:00:00Z',
  },
];

/* Mock Categories */
export const mockCategories = [
  { id: 'battery', name: 'Batteries', count: 245 },
  { id: 'capacitor', name: 'Capacitors', count: 1850 },
  { id: 'resistor', name: 'Resistors', count: 2340 },
  { id: 'diode', name: 'Diodes', count: 580 },
  { id: 'ic', name: 'ICs & Chips', count: 3200 },
  { id: 'microcontroller', name: 'Microcontrollers', count: 890 },
  { id: 'connector', name: 'Connectors', count: 1200 },
  { id: 'sensor', name: 'Sensors', count: 740 },
  { id: 'led', name: 'LEDs', count: 560 },
  { id: 'motor', name: 'Motors', count: 340 },
  { id: 'display', name: 'Displays', count: 420 },
  { id: 'relay', name: 'Relays', count: 280 },
  { id: 'development_board', name: 'Dev Boards', count: 450 },
  { id: 'iot', name: 'IoT Modules', count: 320 },
  { id: 'robotics', name: 'Robotics Kits', count: 180 },
];

/* Exported Collections */
export const allProducts = mockProducts;
export const allSuppliers = mockSuppliers;
export const allReviews = mockReviews;
export const allUsers = mockUsers;
export const allForumThreads = mockForumThreads;
export const allRFQs = mockRFQs;
